version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./dbexport.sql:/docker-entrypoint-initdb.d/dbexport.sql

  
  server:
    image: jriley9000/fee_schedule_server
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fee_schedule
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: jriley9000/fee_schedule_react_tsx
    volumes:
      - ./frontend:/fee_schedule_react_tsx
    environment:
      - REACT_APP_API_URL=http://fee-schedule-server:8080
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  db-data:
