/*
 * CorpFees
 *
 * API for the Corp Fees central.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"database/sql"
	"log"
	"os"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	sw "github.com/Jriles/fee_schedule_server/go"
	"github.com/gin-gonic/gin"

	//
	_ "github.com/lib/pq"
)

var db_conn = os.Getenv("FEE_SCHEDULE_SERVER_DB_CONN")

// ApiMiddleware will add the db connection to the context
func ApiMiddleware(db *sql.DB) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Set("databaseConn", db)
		c.Next()
	}
}

func main() {
	log.Printf("Server started")
	db, err := sql.Open("postgres", db_conn)
	if err != nil {
		log.Fatal("Failed to open a DB connection: ", err)
	}

	router := sw.NewRouter()

	router.Use(ApiMiddleware(db))

	log.Fatal(router.Run(":8080"))
}
