/*
 * CorpFees
 *
 * API for the Corp Fees central.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package fee_schedule_server

type CreateServiceVariantSchema struct {

	ServiceId string `json:"service_id"`

	StateCost int32 `json:"state_cost"`

	PerPageStateCost int32 `json:"per_page_state_cost,omitempty"`

	ServiceAttributeValueIds []string `json:"service_attribute_value_ids"`
}
