/*
 * CorpFees
 *
 * API for the Corp Fees central.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package fee_schedule_server

type VariantResponse struct {

	Currency string `json:"currency"`

	Amount float32 `json:"amount"`
}
